spring.application.name=ProyectoSis414

spring.datasource.url=jdbc:postgresql://dpg-d8718vn7f7vs738e7h2g-a.oregon-postgres.render.com:5432/mydb_vsiaf_7bitssinexito

spring.datasource.username=mydb_vsiaf_7bitssinexito_user

spring.datasource.password=a3eYVFnGfJr7rBJpE1UeBkF7MXyAGVgA

spring.datasource.driver-class-name=org.postgresql.Driver

server.forward-headers-strategy=framework

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect