spring.application.name=ProyectoSis414
spring.datasource.url=jdbc:postgresql://dpg-d87l320jo6nc73bb2cb0-a.ohio-postgres.render.com/estado_bd?sslmode=require
spring.datasource.username=estado_bd_user
spring.datasource.password=gxzyJztLHzOxPjvJH4W3XbqLdf7eChDK
spring.datasource.driver-class-name=org.postgresql.Driver
server.forward-headers-strategy=framework
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialet=org.hibernate.dialect.PostgreSQLDialect